// Data used to populate my resume page and its components.

import { ResumeData } from '@/lib/types/Resume';

export const RESUME_DATA: ResumeData = {
  experiences: [
    {
      id: 'exp1',
      company: 'Saga Education',
      title: 'Software Engineer III',
      location: 'Remote',
      startDate: 'July 2022',
      endDate: 'May 2025',
      current: false,
      highlights: [
        'Developed EdTech, including dashboards, games and collaboration tools, used by program administrators, math tutors and students',
        'Built TypeScript GraphQL APIs on Node.js with performant SQL and MongoDB database operations',
        'Developed frontends with Haxe, JavaScript, HTML, Sass and Svelte',
        "Collaborated with artists to design and script an automated asset pipeline in Ruby, streamlining the ingestion of layered Photoshop files for integration with Saga's largest educational game title",
        "Administered builds and deployment of Saga's flagship products to QA and production environments",
        'Developed unit tests, refactored legacy tests, and created new test infrastructure to improve code maintainability',
      ],
    },
    {
      id: 'exp2',
      company: 'Oregon State University',
      title: 'Graduate Teaching Assistant',
      location: 'Corvallis, Oregon',
      startDate: 'Dec 2021',
      endDate: 'March 2022',
      current: false,
      highlights: [
        'Lectured, facilitated, and graded two weekly studios each consisting of 25 students',
        'Accommodated studios to be hybrid (available remote and in-person) so that students aﬀected by COVID-19 could still attend',
        'Taught students how to use Microsoft Excel and Resilience Analysis and Planning Tool (RAPT)',
        'Taught students teamwork and problem-solving skills',
        'Managed group work allocation and communication conflicts',
      ],
    },
    {
      id: 'exp3',
      company: 'Oregon State University',
      title: 'Graduate Research Assistant',
      location: 'Corvallis, Oregon',
      startDate: 'Sept 2020',
      endDate: 'Dec 2021',
      current: false,
      highlights: [
        'Created computer science teaching materials for middle school math teachers utilizing physical games and an educational coding language',
        'Trained and managed a team of 3 undergraduate student researchers',
        'Gathered information on curriculum and teacher effectiveness by observing and conducting interviews with middle school teachers',
        'Lectured, facilitated, and graded for engineering class studios',
      ],
    },
    {
      id: 'exp4',
      company: 'Oregon State University',
      title: 'Computer Science Teaching Assistant',
      location: 'Corvallis, Oregon',
      startDate: 'Dec 2017',
      endDate: 'Dec 2019',
      current: false,
      highlights: [
        'Taught students computer science fundamentals and programming skills in Python and C++',
        'Instructed and guided labs of 15 to 30 students',
        'Hosted office hours for students in need of assistance',
        'Graded up to 20 programming assignments per week',
        'Lectured as a substitute instructor for classes of over 50',
      ],
    },
    {
      id: 'exp5',
      company: 'McAfee',
      title: 'Software Engineering Intern',
      location: 'Hillsboro, Oregon',
      startDate: 'April 2019',
      endDate: 'Sept 2019',
      current: false,
      highlights: [
        'Successfully administered the migration of software defect tracking information from Bugzilla to Jira for all software development teams at McAfee as a part of an initiative to streamline agile processes',
        'Wrote SQL and JQL queries to gather relevant product defect information for management reports',
      ],
    },
    {
      id: 'exp6',
      company: 'U.S. Bank',
      title: 'Software Development Intern',
      location: 'Portland, Oregon',
      startDate: 'June 2018',
      endDate: 'Sept 2018',
      current: false,
      highlights: ['Developed tools in C# and Perl for credit card information processing'],
    },
  ],
  educations: [
    {
      id: 'edu1',
      institution: 'Oregon State University',
      degree: 'M.S. Computer Science Education',
      location: 'Corvallis, Oregon',
      graduatedDate: '2022',
      gpa: '4.0',
      highlights: ['Thesis'],
    },
    {
      id: 'edu2',
      institution: 'Oregon State University',
      degree: 'Graduate Certificate in College and University Teaching',
      location: 'Corvallis, Oregon',
      graduatedDate: '2021',
      gpa: '4.0',
      highlights: [
        'GCCUT',
        'Created syllabi and lesson content for university computer science courses',
      ],
    },
    {
      id: 'edu3',
      institution: 'Oregon State University',
      degree: 'B.S. Computer Science',
      location: 'Corvallis, Oregon',
      graduatedDate: '2020',
      gpa: '3.7',
      highlights: [],
    },
    {
      id: 'edu4',
      institution: 'Wilson High School',
      degree: 'High School Diploma',
      location: 'Portland, Oregon',
      graduatedDate: '2016',
      gpa: '3.6',
      highlights: [],
    },
  ],
  skills: {
    technical: [
      'TypeScript',
      'JavaScript',
      'Python',
      'C++',
      'C#',
      'Ruby',
      'Haxe',
      'Perl',
      'GraphQL',
      'Node.js',
      'React',
      'Svelte',
      'Next.js',
      'HTML',
      'Sass',
      'Tailwind CSS',
    ],
    tools: ['Git', 'MongoDB', 'SQL', 'Jira', 'Sanity CMS', 'Vercel', 'Photoshop'],
    languages: [{ name: 'English', proficiency: 'Native' }],
  },
};
